CREATE SCHEMA IF NOT EXISTS manual_qc_lab;

CREATE TABLE IF NOT EXISTS manual_qc_lab.schema_migrations (
    version text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS manual_qc_lab.t_qc_daily_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_date date NOT NULL,
    scene_name varchar(256) NOT NULL,
    group_name varchar(128) NOT NULL DEFAULT '',
    employee_id varchar(64) NOT NULL,
    project_name varchar(64) NOT NULL DEFAULT '',
    annotation_total integer NOT NULL DEFAULT 0,
    annotation_submitted integer NOT NULL DEFAULT 0,
    good_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
    bad_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
    option_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
    confirmed_by varchar(64),
    confirmed_at timestamptz,
    executed_by varchar(64),
    executed_at timestamptz,
    execution_note text,
    computed_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_qc_daily_snapshot_dimension
        UNIQUE (stat_date, scene_name, group_name, employee_id),
    CONSTRAINT ck_qc_snapshot_annotation_counts CHECK (
        annotation_total >= 0
        AND annotation_submitted >= 0
        AND annotation_submitted <= annotation_total
    ),
    CONSTRAINT ck_qc_snapshot_metric_objects CHECK (
        jsonb_typeof(good_metrics) = 'object'
        AND jsonb_typeof(bad_metrics) = 'object'
        AND jsonb_typeof(option_metrics) = 'object'
    )
);

CREATE INDEX IF NOT EXISTS idx_qc_daily_snapshot_date_scene
    ON manual_qc_lab.t_qc_daily_snapshot (stat_date DESC, scene_name);

CREATE INDEX IF NOT EXISTS idx_qc_daily_snapshot_group
    ON manual_qc_lab.t_qc_daily_snapshot (stat_date DESC, scene_name, group_name);

CREATE INDEX IF NOT EXISTS idx_qc_daily_snapshot_employee
    ON manual_qc_lab.t_qc_daily_snapshot (employee_id, stat_date DESC);

CREATE INDEX IF NOT EXISTS idx_qc_daily_snapshot_project
    ON manual_qc_lab.t_qc_daily_snapshot (project_name, stat_date DESC);

INSERT INTO manual_qc_lab.schema_migrations (version)
VALUES ('001_snapshot_jsonb_v20260709')
ON CONFLICT (version) DO NOTHING;
