DO $migration$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'manual_qc_lab'
          AND table_name = 't_qc_daily_snapshot'
          AND column_name = 'good_annotation_submitted'
    ) THEN
        ALTER TABLE manual_qc_lab.t_qc_daily_snapshot
            RENAME TO t_qc_daily_snapshot_legacy;

        CREATE TABLE manual_qc_lab.t_qc_daily_snapshot (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            stat_date date NOT NULL,
            scene_name varchar(256) NOT NULL,
            group_name varchar(128) NOT NULL DEFAULT '',
            employee_id varchar(64) NOT NULL,
            project_name varchar(64) NOT NULL DEFAULT '',
            annotation_total integer NOT NULL DEFAULT 0,
            annotation_submitted integer NOT NULL DEFAULT 0,
            good_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
            bad_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
            option_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
            confirmed_by varchar(64),
            confirmed_at timestamptz,
            executed_by varchar(64),
            executed_at timestamptz,
            execution_note text,
            computed_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_qc_daily_snapshot_dimension
                UNIQUE (stat_date, scene_name, group_name, employee_id),
            CONSTRAINT ck_qc_snapshot_annotation_counts CHECK (
                annotation_total >= 0
                AND annotation_submitted >= 0
                AND annotation_submitted <= annotation_total
            ),
            CONSTRAINT ck_qc_snapshot_metric_objects CHECK (
                jsonb_typeof(good_metrics) = 'object'
                AND jsonb_typeof(bad_metrics) = 'object'
                AND jsonb_typeof(option_metrics) = 'object'
            )
        );

        INSERT INTO manual_qc_lab.t_qc_daily_snapshot (
            stat_date,
            scene_name,
            group_name,
            employee_id,
            project_name,
            annotation_total,
            annotation_submitted,
            good_metrics,
            bad_metrics,
            option_metrics,
            confirmed_by,
            confirmed_at,
            executed_by,
            executed_at,
            execution_note,
            computed_at,
            updated_at
        )
        SELECT
            legacy.stat_date,
            legacy.scene_name,
            legacy.group_name,
            legacy.employee_id,
            legacy.project_name,
            legacy.annotation_total,
            legacy.annotation_submitted,
            jsonb_build_object(
                'annotation_total', legacy.good_annotation_submitted,
                'annotation_submitted', legacy.good_annotation_submitted,
                'expect_alloc', legacy.good_accept_assigned,
                'actual_alloc', legacy.good_accept_assigned,
                'actual_complete', legacy.good_accept_completed,
                'correct', legacy.good_accept_passed,
                'incorrect', legacy.good_accept_rejected,
                'conclusion', lower(legacy.overall_conclusion),
                'expect_pass', legacy.good_accept_passed,
                'expect_reject', legacy.good_accept_rejected,
                'actual_pass', legacy.good_accept_passed,
                'actual_reject', legacy.good_accept_rejected,
                'exec_status', NULL
            ),
            jsonb_build_object(
                'annotation_total', legacy.bad_annotation_submitted,
                'annotation_submitted', legacy.bad_annotation_submitted,
                'expect_alloc', legacy.bad_accept_assigned,
                'actual_alloc', legacy.bad_accept_assigned,
                'actual_complete', legacy.bad_accept_completed,
                'correct', legacy.bad_accept_passed,
                'incorrect', legacy.bad_accept_rejected,
                'conclusion', lower(legacy.overall_conclusion),
                'expect_pass', legacy.bad_accept_passed,
                'expect_reject', legacy.bad_accept_rejected,
                'actual_pass', legacy.bad_accept_passed,
                'actual_reject', legacy.bad_accept_rejected,
                'exec_status', NULL
            ),
            CASE
                WHEN legacy.option_metrics = '{}'::jsonb THEN '{}'::jsonb
                ELSE jsonb_build_object(
                    '待确认问题标签',
                    COALESCE((
                        SELECT jsonb_object_agg(
                            metric.key,
                            jsonb_build_object(
                                'annotation_total', metric.value::integer,
                                'annotation_submitted', metric.value::integer,
                                'expect_alloc', 0,
                                'actual_alloc', 0,
                                'actual_complete', 0,
                                'correct', 0,
                                'incorrect', 0,
                                'conclusion', NULL,
                                'expect_pass', 0,
                                'expect_reject', 0,
                                'actual_pass', 0,
                                'actual_reject', 0,
                                'exec_status', NULL
                            )
                        )
                        FROM jsonb_each_text(legacy.option_metrics) AS metric
                    ), '{}'::jsonb)
                )
            END,
            legacy.confirmed_by,
            legacy.confirmed_at,
            legacy.executed_by,
            legacy.executed_at,
            concat_ws(
                E'\n',
                legacy.conclusion_reason,
                CASE
                    WHEN legacy.execution <> '{}'::jsonb
                    THEN 'legacy_execution=' || legacy.execution::text
                END
            ),
            legacy.computed_at,
            legacy.updated_at
        FROM manual_qc_lab.t_qc_daily_snapshot_legacy AS legacy;

        DROP TABLE manual_qc_lab.t_qc_daily_snapshot_legacy;
    END IF;
END
$migration$;

CREATE INDEX IF NOT EXISTS idx_qc_daily_snapshot_date_scene
    ON manual_qc_lab.t_qc_daily_snapshot (stat_date DESC, scene_name);
CREATE INDEX IF NOT EXISTS idx_qc_daily_snapshot_group
    ON manual_qc_lab.t_qc_daily_snapshot (stat_date DESC, scene_name, group_name);
CREATE INDEX IF NOT EXISTS idx_qc_daily_snapshot_employee
    ON manual_qc_lab.t_qc_daily_snapshot (employee_id, stat_date DESC);
CREATE INDEX IF NOT EXISTS idx_qc_daily_snapshot_project
    ON manual_qc_lab.t_qc_daily_snapshot (project_name, stat_date DESC);
CREATE INDEX IF NOT EXISTS idx_qc_daily_snapshot_good_exec
    ON manual_qc_lab.t_qc_daily_snapshot
        (stat_date, scene_name, group_name, employee_id)
    WHERE good_metrics->>'exec_status' = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_qc_daily_snapshot_bad_exec
    ON manual_qc_lab.t_qc_daily_snapshot
        (stat_date, scene_name, group_name, employee_id)
    WHERE bad_metrics->>'exec_status' = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_qc_daily_snapshot_option_metrics
    ON manual_qc_lab.t_qc_daily_snapshot
    USING gin (option_metrics jsonb_path_ops);

INSERT INTO manual_qc_lab.schema_migrations (version)
VALUES ('002_migrate_legacy_snapshot')
ON CONFLICT (version) DO NOTHING;
