CREATE TABLE IF NOT EXISTS manual_qc_lab.t_portal_view_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id varchar(64) NOT NULL,
    page_key varchar(128) NOT NULL,
    view_name varchar(128) NOT NULL DEFAULT '默认视图',
    view_type varchar(32) NOT NULL DEFAULT 'dashboard',
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    version integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_portal_view_config_owner_page_name
        UNIQUE (owner_id, page_key, view_name),
    CONSTRAINT ck_portal_view_config_type
        CHECK (view_type IN ('dashboard', 'data_workbench')),
    CONSTRAINT ck_portal_view_config_json
        CHECK (jsonb_typeof(config) = 'object'),
    CONSTRAINT ck_portal_view_config_version
        CHECK (version > 0)
);

CREATE INDEX IF NOT EXISTS idx_portal_view_config_page_owner
    ON manual_qc_lab.t_portal_view_config (page_key, owner_id, updated_at DESC);

INSERT INTO manual_qc_lab.schema_migrations (version)
VALUES ('004_create_portal_view_config')
ON CONFLICT (version) DO NOTHING;
