CREATE TABLE IF NOT EXISTS manual_qc_lab.t_agent_run (
    id varchar(64) PRIMARY KEY,
    agent_id varchar(128) NOT NULL,
    agent_name varchar(256) NOT NULL,
    title varchar(256) NOT NULL,
    prompt text NOT NULL,
    actor_id varchar(128) NOT NULL DEFAULT 'local-user',
    status varchar(32) NOT NULL DEFAULT 'queued',
    model varchar(256),
    repository_path text NOT NULL,
    base_revision varchar(128) NOT NULL,
    worktree_path text,
    branch_name varchar(256),
    opencode_session_id varchar(128),
    exit_code integer,
    result_summary text,
    failure_code varchar(64),
    failure_reason text,
    artifact_path text,
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    finished_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_agent_run_status CHECK (
        status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')
    )
);

CREATE INDEX IF NOT EXISTS idx_agent_run_created
    ON manual_qc_lab.t_agent_run (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_run_status_updated
    ON manual_qc_lab.t_agent_run (status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_run_agent_created
    ON manual_qc_lab.t_agent_run (agent_id, created_at DESC);

CREATE TABLE IF NOT EXISTS manual_qc_lab.t_agent_run_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id varchar(64) NOT NULL
        REFERENCES manual_qc_lab.t_agent_run(id) ON DELETE CASCADE,
    sequence integer NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    event_type varchar(128) NOT NULL,
    source varchar(64) NOT NULL DEFAULT 'platform',
    channel varchar(32),
    summary text NOT NULL DEFAULT '',
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT uq_agent_run_event_sequence UNIQUE (run_id, sequence),
    CONSTRAINT ck_agent_run_event_payload CHECK (jsonb_typeof(payload) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_agent_run_event_cursor
    ON manual_qc_lab.t_agent_run_event (run_id, sequence);

INSERT INTO manual_qc_lab.schema_migrations (version)
VALUES ('005_create_agent_runtime')
ON CONFLICT (version) DO NOTHING;
