CREATE TABLE IF NOT EXISTS manual_qc_lab.t_gongzuo_machine (
    id varchar(64) PRIMARY KEY,
    workspace varchar(16) NOT NULL,
    name varchar(160) NOT NULL,
    token_hash varchar(64) NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'online',
    capacity integer NOT NULL,
    capabilities jsonb NOT NULL DEFAULT '{}'::jsonb,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_gongzuo_machine_workspace CHECK (workspace IN ('personal', 'team')),
    CONSTRAINT ck_gongzuo_machine_status CHECK (status IN ('online', 'paused', 'draining')),
    CONSTRAINT ck_gongzuo_machine_capacity CHECK (capacity BETWEEN 1 AND 32),
    CONSTRAINT ck_gongzuo_machine_capabilities CHECK (jsonb_typeof(capabilities) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_gongzuo_machine_workspace_seen
    ON manual_qc_lab.t_gongzuo_machine (workspace, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS manual_qc_lab.t_gongzuo_run (
    id varchar(64) PRIMARY KEY,
    workspace varchar(16) NOT NULL,
    item_id varchar(64) NOT NULL,
    attempt integer NOT NULL,
    retry_of varchar(64) REFERENCES manual_qc_lab.t_gongzuo_run(id),
    actor_id varchar(128) NOT NULL,
    instruction text NOT NULL,
    prompt_snapshot text NOT NULL,
    item_snapshot jsonb NOT NULL,
    context_snapshot jsonb NOT NULL,
    capability_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
    capability_candidate_id varchar(64),
    context_version_id varchar(64) NOT NULL,
    context_revision_no integer NOT NULL,
    state varchar(24) NOT NULL DEFAULT 'queued',
    engine varchar(24) NOT NULL,
    runtime varchar(16) NOT NULL,
    image text,
    requested_machine_id varchar(64) REFERENCES manual_qc_lab.t_gongzuo_machine(id),
    machine_id varchar(64) REFERENCES manual_qc_lab.t_gongzuo_machine(id),
    lease_id varchar(64),
    lease_expires_at timestamptz,
    model varchar(256),
    sandbox varchar(32) NOT NULL DEFAULT 'read-only',
    session_id varchar(256),
    repository_path text,
    repository_revision varchar(128),
    directory text NOT NULL,
    branch varchar(256),
    environment_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    result text,
    result_payload jsonb,
    artifact_candidates jsonb NOT NULL DEFAULT '[]'::jsonb,
    evidence_candidates jsonb NOT NULL DEFAULT '[]'::jsonb,
    exit_code integer,
    failure_code varchar(64),
    error text,
    cancellation_requested_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    claimed_at timestamptz,
    started_at timestamptz,
    finished_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_gongzuo_run_attempt UNIQUE (workspace, item_id, attempt),
    CONSTRAINT ck_gongzuo_run_workspace CHECK (workspace IN ('personal', 'team')),
    CONSTRAINT ck_gongzuo_run_state CHECK (
        state IN ('queued', 'claimed', 'running', 'pause_requested', 'paused',
                  'cancelling', 'cancelled', 'succeeded', 'failed', 'unavailable')
    ),
    CONSTRAINT ck_gongzuo_run_engine CHECK (engine IN ('codex', 'opencode')),
    CONSTRAINT ck_gongzuo_run_runtime CHECK (runtime IN ('native', 'docker')),
    CONSTRAINT ck_gongzuo_run_sandbox CHECK (sandbox IN ('read-only', 'workspace-write')),
    CONSTRAINT ck_gongzuo_run_snapshots CHECK (
        jsonb_typeof(item_snapshot) = 'object'
        AND jsonb_typeof(context_snapshot) = 'object'
        AND jsonb_typeof(capability_snapshot) = 'array'
        AND jsonb_typeof(environment_snapshot) = 'object'
        AND jsonb_typeof(artifact_candidates) = 'array'
        AND jsonb_typeof(evidence_candidates) = 'array'
    )
);

ALTER TABLE manual_qc_lab.t_gongzuo_run
    ADD COLUMN IF NOT EXISTS capability_candidate_id varchar(64);

CREATE INDEX IF NOT EXISTS idx_gongzuo_run_workspace_created
    ON manual_qc_lab.t_gongzuo_run (workspace, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gongzuo_run_claim_queue
    ON manual_qc_lab.t_gongzuo_run (workspace, state, created_at)
    WHERE state = 'queued';
CREATE INDEX IF NOT EXISTS idx_gongzuo_run_item_attempt
    ON manual_qc_lab.t_gongzuo_run (workspace, item_id, attempt DESC);

CREATE TABLE IF NOT EXISTS manual_qc_lab.t_gongzuo_run_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id varchar(64) NOT NULL
        REFERENCES manual_qc_lab.t_gongzuo_run(id) ON DELETE CASCADE,
    sequence integer NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    event_type varchar(128) NOT NULL,
    source varchar(64) NOT NULL,
    channel varchar(32),
    summary text NOT NULL DEFAULT '',
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_gongzuo_run_event_sequence UNIQUE (run_id, sequence),
    CONSTRAINT ck_gongzuo_run_event_payload CHECK (jsonb_typeof(payload) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_gongzuo_run_event_cursor
    ON manual_qc_lab.t_gongzuo_run_event (run_id, sequence);

INSERT INTO manual_qc_lab.schema_migrations (version)
VALUES ('009_gongzuo_runtime')
ON CONFLICT (version) DO NOTHING;
